language: go

go:
  - 1.8.x
  - 1.9

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - go vet
  - go test -race -coverprofile=coverage.txt -covermode=atomic
  - $GOPATH/bin/goveralls -coverprofile=coverage.txt -service=travis-ci -repotoken $COVERALLS_TOKEN

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    secure: "BGL7l1porJZ2J+oKnG82x6w0GXIq05x2IQsyPTEBzNK0H12AeWWT6tAW6x9jI6x1FgsvbqULxU4lXxKax5UqSkPkdrNZ6izVbVkbgO6OtL2Xz6U/ASQma70eyV81GeWgG0A5sbgNJIKs8+ADgNk1fLs4WCkUjcvZVvqQjqltil15TmA5DjUkMRc94i2Y6SzdYtIvhQIheiIskv+Glq6f8N1XZ5XK2mi83rKFlSjyreLVEmhv2TDCpo4A1MnqZhFVaiOfAZxuHsfpAMD/zZ91dI/ge/T5VzlKt1QhABva7ZQJ5NbbprsrsiTtEV26cougLnpVTTYCY4ZCqoyPQLg5iTkyRTD2/BcENYcqQVXinKZR/tw1MGxds5MNYVKLKzaiuY4PP0HPjrsO+r0cNwnKtk/O6z5R59Umuitknu6+O84B0M3ncQ2tBGAbgiasdCMPP6J6MPQC6ngpp7/jSkXG19cMF+mOWeIxU0FieLMVCfBxI73dt8//oh4dXpmR016nY2i6eVeZJWHEb9j3MM+u37eOapx2hyh2OqD4+5GccMhPyVFMqAZVrNn6UcFoHnnf3iygQG1eC20OsYyVHZi7T3JiGxBWvePtBGwIU4td9j6Cgw22Op/p+CEgrqe/bh+HAu913mp4lsMLXpGd0a4rbkPb0pNcRgYXhNbRASSGbYg="
